//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
namespace webDEMOModel
{
    #region 上下文
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    public partial class webDEMOEntities : ObjectContext
    {
        #region 构造函数
    
        /// <summary>
        /// 请使用应用程序配置文件的“webDEMOEntities”部分中的连接字符串初始化新 webDEMOEntities 对象。
        /// </summary>
        public webDEMOEntities() : base("name=webDEMOEntities", "webDEMOEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// 初始化新的 webDEMOEntities 对象。
        /// </summary>
        public webDEMOEntities(string connectionString) : base(connectionString, "webDEMOEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// 初始化新的 webDEMOEntities 对象。
        /// </summary>
        public webDEMOEntities(EntityConnection connection) : base(connection, "webDEMOEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region 分部方法
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet 属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<member> member
        {
            get
            {
                if ((_member == null))
                {
                    _member = base.CreateObjectSet<member>("member");
                }
                return _member;
            }
        }
        private ObjectSet<member> _member;

        #endregion

        #region AddTo 方法
    
        /// <summary>
        /// 用于向 member EntitySet 添加新对象的方法，已弃用。请考虑改用关联的 ObjectSet&lt;T&gt; 属性的 .Add 方法。
        /// </summary>
        public void AddTomember(member member)
        {
            base.AddObject("member", member);
        }

        #endregion

    }

    #endregion

    #region 实体
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="webDEMOModel", Name="member")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class member : EntityObject
    {
        #region 工厂方法
    
        /// <summary>
        /// 创建新的 member 对象。
        /// </summary>
        /// <param name="id">id 属性的初始值。</param>
        /// <param name="account">account 属性的初始值。</param>
        /// <param name="password">password 属性的初始值。</param>
        /// <param name="email">email 属性的初始值。</param>
        public static member Createmember(global::System.Int32 id, global::System.String account, global::System.String password, global::System.String email)
        {
            member member = new member();
            member.id = id;
            member.account = account;
            member.password = password;
            member.email = email;
            return member;
        }

        #endregion

        #region 简单属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value, "id");
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int32 _id;
        partial void OnidChanging(global::System.Int32 value);
        partial void OnidChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String account
        {
            get
            {
                return _account;
            }
            set
            {
                OnaccountChanging(value);
                ReportPropertyChanging("account");
                _account = StructuralObject.SetValidValue(value, false, "account");
                ReportPropertyChanged("account");
                OnaccountChanged();
            }
        }
        private global::System.String _account;
        partial void OnaccountChanging(global::System.String value);
        partial void OnaccountChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String password
        {
            get
            {
                return _password;
            }
            set
            {
                OnpasswordChanging(value);
                ReportPropertyChanging("password");
                _password = StructuralObject.SetValidValue(value, false, "password");
                ReportPropertyChanged("password");
                OnpasswordChanged();
            }
        }
        private global::System.String _password;
        partial void OnpasswordChanging(global::System.String value);
        partial void OnpasswordChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String email
        {
            get
            {
                return _email;
            }
            set
            {
                OnemailChanging(value);
                ReportPropertyChanging("email");
                _email = StructuralObject.SetValidValue(value, false, "email");
                ReportPropertyChanged("email");
                OnemailChanged();
            }
        }
        private global::System.String _email;
        partial void OnemailChanging(global::System.String value);
        partial void OnemailChanged();

        #endregion

    }

    #endregion

}
